export const ProjectData = [
  {
    img: "/img/cocktail.png",
    title:'Cocktail Recipe',
    description:`API를 활용하여 다양한 칵테일레시피를 제공하는 반응형 웹사이트 입니다.`,
    list1:'search 기능 구현',
    list2:'메뉴필터링 기능',
    list3:'찜하기 기능',
    list4:'로그인기능(firebase)',
  },
  {
    img: "/img/cocktail.png",
    title:'플래너앱',
    description:`JavaScript를 이용하여 만든 플래너앱입니다.`,
    list1:' todo-list 구현',
    list2:'d-day기능 구현',
    list3:'캘린더',
  },
  {
    img: "/img/cocktail.png",
    title:'플래너앱',
    description:`JavaScript를 이용하여 만든 플래너앱입니다.`,
    list1:' todo-list 구현',
    list2:'d-day기능 구현',
    list3:'캘린더',
  },
  {
    img: "/img/cocktail.png",
    title:'플래너앱',
    description:`JavaScript를 이용하여 만든 플래너앱입니다.`,
    list1:' todo-list 구현',
    list2:'d-day기능 구현',
    list3:'캘린더',
  },
]